### PR TITLE
Add circle-ci integration: build with Java 8, 10 and 12

### PR DESCRIPTION
**Pull request by Mingun**
Example: https://circleci.com/gh/Mingun/TlkEdit-EE

### CODE REVIEW

**Comment by Mingun** [comment]
@calgacus , it seems that you do not activate circle-ci builds:
SetUpProjects

**Comment by calgacus** [comment]
@Mingun 
Doh!   Ok try now.

**Comment by Mingun** [comment]
It seems, that building of PR is disabled. Please check that setting, for me it was disabled by default:

Step1
Step2

**Comment by calgacus** [comment]
OK, try now.

**Pull request merged**
